import React from "react";
import MonetizationOnIcon from "@material-ui/icons/AttachMoney";
import ShowChartIcon from "@material-ui/icons/ShowChart";
import { buildChartData } from "helpers/pgChartsHelper";
import { numberFormatter, deriveDateFromIndex } from "helpers/utils";

const drawXAxis = (data, timeAgg) => {
  const time = {};

  data &&
    data.forEach(o => {
      if (o.hasOwnProperty("timeAgg")) {
        if (!time.hasOwnProperty(o.timeAgg)) {
          time[o.timeAgg] = true;
        }
      } else {
        const date =
          o.dateindex || o.weekindex || o.monthindex || o.quarterindex;
        time[deriveDateFromIndex(date, timeAgg)] = true;
      }
    });

  return Object.keys(time);
};

export const chartOptionsConfigFn = (
  data,
  dimensionKey,
  dimensions,
  metricsConfig,
  graphType,
  isStack,
  timeAgg
) => {
  return {
    tooltip: {
      trigger: "axis",
      axisPointer: {
        type: "shadow",
      },
      formatter: params => {
        let tooltip = "";
        let date = "";
        params.forEach(series => {
          const metric = metricsConfig.find(
            cm => series.data.name === cm.title
          );
          date = `${series.axisValue} <br/> `;
          tooltip += `${series.marker} ${series.seriesName}: ${numberFormatter(
            metric.type,
            series.data.value,
            metric.isDecimal,
            metric.decimalPoints,
            metric.formatting
          )}</br>`;
        });
        return date + tooltip;
      },
    },
    legend: {
      data: Object.values(dimensions)
        .map(item =>
          item.map(dim =>
            metricsConfig.map(m => `${dim.replace(/_/g, " ")} - ${m.title}`)
          )
        )
        .flat()
        .flat(),
    },
    grid: {
      left: "2%",
      right: "2%",
      top: "7%",
      containLabel: true,
    },
    toolbox: {
      show: false,
    },
    dataZoom: {
      type: "slider",
      show: true,
      realtime: true,
      showDataShadow: true,
      zoomLock: false,
      start: 0,
      end: 100,
      bottom: 10,
    },
    xAxis: {
      type: "category",
      boundaryGap: true,
      axisTick: {
        alignWithLabel: true,
      },
      data: drawXAxis(data, timeAgg),
    },
    yAxis: [{ type: "value" }, { type: "value" }],
    series: buildChartData(
      data,
      dimensionKey,
      dimensions,
      metricsConfig,
      graphType,
      isStack
    ),
    barMaxWidth: 40,
    // color: ['#238FC5', '#238FC595', '#238FC585']
    // // color: ['#238FC5', '#55BD78', '#9A4059', '#ffa600', '#E4AF4F', '#d48265', '#384A50', '#91c7ae', '#215967', '#8C7F7E',]
  };
};

// We need to follow this config to add up the required meta data for the metrics based on table/charts
// you can create multiple configs like this and use it based on the requirements
const dateSystem = {
  title: "Date",
  key: "date",
  isDecimal: false,
  decimalPoints: 0,
  formatting: false,
  type: "DATE",
  align: "left",
};

const headlineSystem = {
  title: "Headline",
  key: "",
  isDecimal: false,
  decimalPoints: 0,
  formatting: false,
  type: "TEXT",
  align: "left",
};

const bodySystem = {
  title: "Body",
  key: "",
  isDecimal: false,
  decimalPoints: 0,
  formatting: false,
  type: "TEXT",
  align: "left",
};

const descriptionSystem = {
  title: "Description",
  key: "",
  isDecimal: false,
  decimalPoints: 0,
  formatting: false,
  type: "TEXT",
  align: "left",
};

const creativeSystem = {
  title: "Creative",
  key: "",
  isDecimal: false,
  decimalPoints: 0,
  formatting: false,
  type: "TEXT",
  align: "left",
};

export const dataConfig = {
  date: dateSystem,
  dateindex: dateSystem,
  weekindex: dateSystem,
  monthindex: dateSystem,
  quarterindex: dateSystem,
  name: {
    title: "Name",
    key: "name",
    isDecimal: false,
    decimalPoints: 0,
    formatting: false,
    type: "TEXT",
    align: "left",
  },
  channel: {
    title: "Channel",
    key: "Channel",
    isDecimal: false,
    decimalPoints: 0,
    formatting: false,
    type: "TEXT",
    align: "left",
  },
  category: {
    title: "Category",
    key: "Category",
    isDecimal: false,
    decimalPoints: 0,
    formatting: false,
    type: "TEXT",
    align: "left",
  },
  clicks: {
    title: "Clicks",
    key: "clicks",
    value: "clicks",
    isDecimal: false,
    decimalPoints: 0,
    formatting: true,
    type: "NUMBER",
    align: "right",
  },
  impressions: {
    title: "Impressions",
    key: "impressions",
    value: "impressions",
    isDecimal: false,
    decimalPoints: 0,
    formatting: true,
    type: "NUMBER",
    align: "right",
  },
  revenue: {
    title: "Revenue",
    key: "revenue",
    cardTitle: "Revenue",
    icon: <MonetizationOnIcon />,
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "CURRENCY",
    align: "right",
  },
  commission: {
    title: "Commission",
    cardTitle: "Commission",
    color: "#238FC5",
    icon: <MonetizationOnIcon />,
    key: "spend",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "CURRENCY",
    align: "right",
  },
  ctr: {
    title: "CTR",
    key: "ctr",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "PERCENTAGE",
    align: "left",
  },
  vtr: {
    title: "VTR",
    key: "vtr",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "PERCENTAGE",
    align: "right",
  },
  engine: {
    title: "Engine",
    key: "spend",
    isDecimal: false,
    decimalPoints: 0,
    formatting: false,
    type: "TEXT",
    align: "left",
  },
  brand: {
    title: "Search Type",
    key: "spend",
    isDecimal: false,
    decimalPoints: 0,
    formatting: false,
    type: "TEXT",
    align: "left",
  },
  target: {
    title: "Target",
    key: "target",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "CURRENCY",
    align: "right",
  },
  transactions: {
    title: "Transactions",
    cardTitle: "Transactions",
    color: "#215967",
    icon: <ShowChartIcon />,
    key: "transactions",
    isDecimal: false,
    decimalPoints: 0,
    formatting: true,
    type: "NUMBER",
    align: "right",
  },
  sessions: {
    title: "Sessions",
    cardTitle: "Transactions",
    color: "#215967",
    icon: <ShowChartIcon />,
    key: "sessions",
    isDecimal: false,
    decimalPoints: 0,
    formatting: true,
    type: "NUMBER",
    align: "right",
  },
  cpa_transactions: {
    title: "CPA Transactions",
    cardTitle: "CPA Transactions",
    color: "#215967",
    icon: <ShowChartIcon />,
    key: "transactions",
    isDecimal: false,
    decimalPoints: 0,
    formatting: true,
    type: "NUMBER",
    align: "right",
  },
  cpa_transaction_value: {
    title: "CPA Transaction value",
    cardTitle: "CPA Transaction value",
    color: "#212367",
    icon: <ShowChartIcon />,
    key: "transactions",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "CURRENCY",
    align: "right",
  },
  cpe_transactions: {
    title: "CPE Transactions",
    cardTitle: "CPE Transactions",
    color: "#215967",
    icon: <ShowChartIcon />,
    key: "transactions",
    isDecimal: false,
    decimalPoints: 0,
    formatting: true,
    type: "NUMBER",
    align: "right",
  },
  cpe_transaction_value: {
    title: "CPE Transaction value",
    cardTitle: "CPE Transaction value",
    color: "#218767",
    icon: <ShowChartIcon />,
    key: "transactions",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "CURRENCY",
    align: "right",
  },
  cpm_transactions: {
    title: "CPM Transactions",
    cardTitle: "CPM Transactions",
    color: "#215967",
    icon: <ShowChartIcon />,
    key: "transactions",
    isDecimal: false,
    decimalPoints: 0,
    formatting: true,
    type: "NUMBER",
    align: "right",
  },
  aov: {
    title: "AOV",
    cardTitle: "AOV",
    color: "#8C7F7E",
    icon: <MonetizationOnIcon />,
    key: "aov",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "CURRENCY",
    align: "right",
    heatMapFactor: "negative",
  },
  cpt: {
    title: "CPT",
    cardTitle: "Cost per Transaction",
    color: "#8C7F7E",
    icon: <MonetizationOnIcon />,
    key: "cpt",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "CURRENCY",
    align: "right",
    heatMapFactor: "negative",
  },
  cpa_cpt: {
    title: "CPA - CPT",
    cardTitle: "CPA - Cost per Transaction",
    color: "#8C7F7E",
    icon: <MonetizationOnIcon />,
    key: "cpt",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "CURRENCY",
    align: "right",
    heatMapFactor: "negative",
  },
  cpe_cpt: {
    title: "CPE - CPT",
    cardTitle: "CPE - Cost per Transaction",
    color: "#8C7F7E",
    icon: <MonetizationOnIcon />,
    key: "cpt",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "CURRENCY",
    align: "right",
    heatMapFactor: "negative",
  },
  cpm_cpt: {
    title: "CPM - CPT",
    cardTitle: "CPM - Cost per Transaction",
    color: "#8C7F7E",
    icon: <MonetizationOnIcon />,
    key: "cpt",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "CURRENCY",
    align: "right",
    heatMapFactor: "negative",
  },
  others_cpt: {
    title: "Others - CPT",
    cardTitle: "Others - Cost per Transaction",
    color: "#8C7F7E",
    icon: <MonetizationOnIcon />,
    key: "others_cpt",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "CURRENCY",
    align: "right",
    heatMapFactor: "negative",
  },
  cpm: {
    title: "CPM",
    key: "cpm",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "CURRENCY",
    align: "right",
    heatMapFactor: "negative",
  },
  cps: {
    title: "CPS",
    key: "cps",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "CURRENCY",
    align: "right",
    heatMapFactor: "negative",
  },
  cvr: {
    title: "CVR",
    cardTitle: "Conversion Rate",
    color: "#E4AF4F",
    icon: <ShowChartIcon />,
    key: "cvr",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "PERCENTAGE",
    align: "left",
  },
  bounce: {
    title: "Bounce %",
    cardTitle: "Bounce %",
    color: "#E4AF4F",
    icon: <ShowChartIcon />,
    key: "bounce",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "PERCENTAGE",
    align: "right",
  },
  session_rate: {
    title: "Session Rate",
    cardTitle: "Session Rate",
    color: "#E4AF4F",
    icon: <ShowChartIcon />,
    key: "cvr",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "PERCENTAGE",
    align: "right",
  },
  roas: {
    title: "ROAS",
    cardTitle: "ROAS",
    color: "#55BD78",
    icon: <MonetizationOnIcon />,
    key: "roas",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "CURRENCY",
    align: "right",
  },
  avt: {
    title: "AVT",
    key: "AVT",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "NUMBER",
    align: "right",
  },
  keyword: {
    title: "Keywords",
    key: "Keywords",
    isDecimal: false,
    decimalPoints: 0,
    formatting: false,
    type: "TEXT",
    align: "left",
  },
  keyword_category: {
    title: "Keyword Category",
    key: "Keyword Category",
    isDecimal: false,
    decimalPoints: 0,
    formatting: false,
    type: "TEXT",
    align: "left",
  },
  campaign_type: {
    title: "Campaign Type",
    key: "label",
    isDecimal: false,
    decimalPoints: 0,
    formatting: false,
    type: "TEXT",
    align: "left",
  },
  audience: {
    title: "Campaign Audience",
    key: "label",
    isDecimal: false,
    decimalPoints: 0,
    formatting: false,
    type: "TEXT",
    align: "left",
  },
  platform: {
    title: "Platform",
    key: "label",
    isDecimal: false,
    decimalPoints: 0,
    formatting: false,
    type: "TEXT",
    align: "left",
  },
  business: {
    title: "Business Line",
    key: "name",
    isDecimal: false,
    decimalPoints: 0,
    formatting: false,
    type: "TEXT",
    align: "left",
  },
  affiliate: {
    title: "Affiliate",
    key: "name",
    isDecimal: false,
    decimalPoints: 0,
    formatting: false,
    type: "TEXT",
    align: "left",
  },
  headline_one: headlineSystem,
  headline_two: headlineSystem,
  headline_three: headlineSystem,
  creative_headline: headlineSystem,
  body: bodySystem,
  creative_body: bodySystem,
  link_description: descriptionSystem,
  creative_link_description: descriptionSystem,
  description_one: descriptionSystem,
  description_two: descriptionSystem,
  site_link: {
    title: "Sitelinks",
    key: "",
    isDecimal: false,
    decimalPoints: 0,
    formatting: false,
    type: "TEXT",
    align: "left",
  },
  call_out: {
    title: "CallOuts",
    key: "",
    isDecimal: false,
    decimalPoints: 0,
    formatting: false,
    type: "TEXT",
    align: "left",
  },
  creative: creativeSystem,
  evergreen_creative: creativeSystem,
  promo_creative: creativeSystem,
  ad_name: {
    title: "Ad Name",
    key: "ad_name",
    isDecimal: false,
    decimalPoints: 0,
    formatting: false,
    type: "TEXT",
    align: "left",
  },
  ad_preview_link: {
    title: "Preview URL",
    key: "ad_preview_link",
    isDecimal: false,
    decimalPoints: 0,
    formatting: false,
    type: "LINK",
    align: "left",
  },
  theme: { ...creativeSystem, ...{ title: "Creative Theme" } },
  size: { ...creativeSystem, ...{ title: "Creative Size" } },
  creative_type: {
    title: "Asset type",
    key: "",
    isDecimal: false,
    decimalPoints: 0,
    formatting: false,
    type: "TEXT",
    align: "left",
  },
  device: {
    title: "Device",
    key: "",
    isDecimal: false,
    decimalPoints: 0,
    formatting: false,
    type: "TEXT",
    align: "left",
  },
  placement: {
    title: "Placements",
    key: "name",
    isDecimal: false,
    decimalPoints: 0,
    formatting: false,
    type: "TEXT",
    align: "left",
  },
  media: {
    title: "Media",
    key: "name",
    isDecimal: false,
    decimalPoints: 0,
    formatting: false,
    type: "TEXT",
    align: "left",
  },
  "total transaction value": {
    title: "Total Transaction value",
    cardTitle: "Total Transaction Value",
    color: "#9A4059",
    icon: <MonetizationOnIcon />,
    key: "name",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "CURRENCY",
    align: "right",
  },
  "avg transaction value": {
    title: "Average Transaction value",
    cardTitle: "Avg. Transaction value",
    color: "#384A50",
    icon: <MonetizationOnIcon />,
    key: "name",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "CURRENCY",
    align: "right",
  },
  "b2c2b transactions": {
    title: "B2C2B transactions",
    cardTitle: "B2C2B transactions",
    color: "#ffa600",
    icon: <ShowChartIcon />,
    key: "name",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "CURRENCY",
    align: "right",
  },
  others_transactions: {
    title: "Others transactions",
    cardTitle: "Others transactions",
    color: "#E4AF4F",
    icon: <ShowChartIcon />,
    key: "name",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "CURRENCY",
    align: "right",
  },
  // Client
  visits: {
    title: "Visits",
    cardTitle: "Visits",
    color: "#238FC5",
    icon: <ShowChartIcon />,
    key: "visits",
    isDecimal: false,
    decimalPoints: 0,
    formatting: true,
    type: "NUMBER",
    align: "left",
  },
  spend: {
    title: "Spend",
    cardTitle: "Spend",
    color: "#238FC5",
    icon: <MonetizationOnIcon />,
    key: "spend",
    value: "spend",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "CURRENCY",
    align: "left",
  },
  spend_target: {
    title: "Targeted Spend",
    cardTitle: "Targeted Spend",
    color: "#238FC5",
    icon: <MonetizationOnIcon />,
    key: "spend_target",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "CURRENCY",
    align: "left",
  },
  leads: {
    title: "Leads",
    cardTitle: "Leads",
    color: "#384A50",
    icon: <ShowChartIcon />,
    key: "leads",
    value: "leads",
    isDecimal: false,
    decimalPoints: 0,
    formatting: true,
    type: "NUMBER",
    align: "left",
  },
  prospects: {
    title: "Prospects",
    cardTitle: "Prospects",
    color: "#7158e2",
    icon: <ShowChartIcon />,
    key: "prospects",
    value: "prospects",
    isDecimal: false,
    decimalPoints: 0,
    formatting: true,
    type: "NUMBER",
    align: "left",
  },
  applications: {
    title: "Applications",
    cardTitle: "# of Applications",
    color: "#B53471",
    icon: <ShowChartIcon />,
    key: "applications",
    value: "applications",
    isDecimal: false,
    decimalPoints: 0,
    formatting: true,
    type: "NUMBER",
    align: "left",
  },
  applications_target: {
    title: "Targeted no.of Applications",
    cardTitle: "Targeted no.of Applications",
    color: "#238FC5",
    icon: <ShowChartIcon />,
    key: "applications_target",
    isDecimal: false,
    decimalPoints: 0,
    formatting: true,
    type: "NUMBER",
    align: "left",
  },
  va: {
    title: "Verified applications",
    cardTitle: "# of verified applications",
    color: "#1B1464",
    icon: <ShowChartIcon />,
    key: "va",
    value: "va",
    isDecimal: false,
    decimalPoints: 0,
    formatting: true,
    type: "NUMBER",
    align: "left",
  },
  cpv: {
    title: "Cost per visit",
    cardTitle: "Cost per visit",
    color: "#ffa600",
    icon: <MonetizationOnIcon />,
    key: "cpv",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "CURRENCY",
    align: "left",
  },
  cpp: {
    title: "CPP",
    cardTitle: "Cost per prospect",
    color: "#ffa600",
    icon: <MonetizationOnIcon />,
    key: "cpp",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "CURRENCY",
    align: "left",
  },
  cpl: {
    title: "CPL",
    cardTitle: "Cost per lead",
    color: "#009432",
    icon: <MonetizationOnIcon />,
    key: "cpl",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "CURRENCY",
    align: "left",
  },
  cpa: {
    title: "CPA",
    cardTitle: "Cost per application",
    color: "#ffa600",
    icon: <MonetizationOnIcon />,
    key: "cpa",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "CURRENCY",
    align: "left",
  },
  cpva: {
    title: "CPvA",
    cardTitle: "Cost per verified application",
    color: "#215967",
    icon: <MonetizationOnIcon />,
    key: "cpva",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "CURRENCY",
    align: "left",
  },
  cpc: {
    title: "CPC",
    cardTitle: "Cost per conversion",
    color: "#8C7F7E",
    icon: <MonetizationOnIcon />,
    key: "cpc",
    isDecimal: true,
    decimalPoints: 2,
    formatting: true,
    type: "CURRENCY",
    align: "left",
  },
  program: {
    title: "Program",
    key: "name",
    isDecimal: false,
    decimalPoints: 0,
    formatting: false,
    type: "TEXT",
    align: "left",
  },

  headline: headlineSystem,
  description: descriptionSystem,
};
